version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    # Bugs
    - govet
    - staticcheck
    - errcheck
    # Naming
    - revive
    # Code smells
    - gocritic
    - exhaustruct
    # Error handling
    - wrapcheck
    - errorlint
    # Testing
    - testifylint

  settings:
    revive:
      rules:
        - name: var-naming
        - name: exported
    exhaustruct:
      exclude:
        - ".*_test\\.go"
