version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    # Bugs
    - govet
    - staticcheck
    - errcheck
    # Naming
    - revive
    # Code smells
    - gocritic
    - exhaustruct
    # Error handling
    - wrapcheck
    - errorlint
    # Testing
    - testifylint

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: exported
  gocritic:
    enabled-checks:
      - newDeref
  exhaustruct:
    exclude:
      - ".*_test\\.go"
